title: DAta Research (DAR - در) Lab - Pakistan
description: Decolonizing data to drive post-colonial reparation an initiative that is aimed at providing comprehensive datasets related to Pakistan to facilitate research and promote knowledge exchange.
